# Generated by Django 2.1.5 on 2019-02-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employee',
            new_name='employees',
        ),
    ]
